# Generated by Django 3.1.4 on 2021-01-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepost',
            name='photo',
            field=models.ImageField(null=True, upload_to='simple_website/images/'),
        ),
        migrations.AlterField(
            model_name='makepost',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
